api:
  image: registry.heroku.com/guarded-scrubland-78590/web
  ports:
    - "3001:8080"
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  links:
    - hub
  expose:
    - "5555"